git_url: ((docker_git_url))
git_branch: ((docker_git_branch))
pivnet_token: ((pivnet_token))
docker_hub_repository: rjain/buildbox

tkgi_product_version: ^1\.20\..*$

internal_registry:
  host: ((harbor_host))
  username: ((harbor_credentials.username))
  password: ((harbor_credentials.password))

docker_image:
  version: ubuntu:24.10
  maintainer: "rahulkj@gmail.com"
  maintainer_name: "Rahul Jain"